# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-09-07 18:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpressionTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_expression', models.CharField(max_length=500)),
                ('tweet', django.contrib.postgres.fields.jsonb.JSONField()),
                ('tweet_id', models.CharField(max_length=20, unique=True)),
                ('average_word_frequency', models.FloatField()),
            ],
        ),
    ]
