#!/usr/bin/env python

"""
Prints stats generated by cProfile.
"""

import pstats
import sys, os


def print_stats(p, strip_dirs=False, sort_by=None):
    stats = None
    for f in os.listdir(p):
        f = os.path.join(p, f)
        if stats is None:
            stats = pstats.Stats(f)
        else:
            stats.add(f)

    if strip_dirs:
        stats.strip_dirs()

    stats.sort_stats(sort_by)
    stats.print_stats()



if __name__ == '__main__':
    import argparse

    parser = argparse.ArgumentParser(__doc__)
    parser.add_argument('profiles', metavar='directory', type=unicode,
                        help='path to director containing profile data files')
    parser.add_argument('-d', '--strip-dirs', action='store_true',
                        help='strip directories from the output')
    parser.add_argument('-s', '--sort',
                        default='cumulative',
                        help='provides the argument given to pstats.Stats#sort_stats')
    args = parser.parse_args()

    print_stats(args.profiles, strip_dirs=args.strip_dirs, sort_by=args.sort)



