# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-09-06 18:45
from __future__ import unicode_literals

from django.db import migrations, models


def copy_intervals(apps, schema_editor):
    from datetime import timedelta

    Card = apps.get_model('flashcards', 'Card')
    for card in Card.objects.all():
        if card.interval is not None:
            card.new_interval = timedelta(days=card.interval)
        if card.last_interval is not None:
            card.new_last_interval = timedelta(days=card.last_interval)
        card.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_field_content_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='new_interval',
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='new_last_interval',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.RunPython(copy_intervals),
    ]
