# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 01:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_drop_old_interval_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtemplate',
            name='requisite_field_types',
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deck',
            name='shared_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
