# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 02:39
from __future__ import unicode_literals

from django.db import migrations, models


def inherit_from_cards(apps, schema_editor):
    Fact = apps.get_model('flashcards', 'Fact')
    for fact in Fact.objects.all():
        cards_suspended = not (
            fact.card_set.filter(active=True)
            .exclude(suspended=True).exists()
        )
        if cards_suspended:
            fact.suspended = cards_suspended
            fact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_make_fact_deck_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(inherit_from_cards),
    ]
