# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-02 23:02
from __future__ import unicode_literals
import re

from django.db import migrations


def new_reading(reading):
    reading = re.sub(ur'^(\w+)\[(\w*)\]', ur'｜\1《\2》',
                     reading, flags=re.UNICODE)
    reading = re.sub(ur' (\w+)\[(\w*)\]', ur'｜\1《\2》',
                     reading, flags=re.UNICODE)
    print reading
    return reading


def convert(apps, schema_editor):
    Fact = apps.get_model('flashcards', 'Fact')
    for fact in Fact.objects.all():
        reading = new_reading(fact.reading)
        fact.reading = reading
        fact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_fact_suspended'),
    ]

    operations = [
        migrations.RunPython(convert),
    ]
