# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-03 00:04
from __future__ import unicode_literals
import re

from django.db import migrations


def new_reading(reading):
    updated = re.sub(ur'^(\w+)\[([\w、／/ 　。－・,-]*)\]', ur'｜\1《\2》',
                     reading, flags=re.UNICODE)
    updated = re.sub(ur'[ 　,](\w+)\[([\w、／/ 　。－・,-]*)\]', ur'｜\1《\2》',
                     updated, flags=re.UNICODE)
    if reading != updated:
        print reading, "  ====>  ", updated
    return updated


def convert(apps, schema_editor):
    Fact = apps.get_model('flashcards', 'Fact')
    for fact in Fact.objects.all():
        reading = new_reading(fact.reading)
        fact.reading = reading
        fact.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_raw_reading_new_format'),
    ]

    operations = [
        migrations.RunPython(convert),
    ]
