# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 03:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0009_raw_reading_new_format_for_unicode_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='undocardreview',
            name='pickled_card',
        ),
        migrations.AddField(
            model_name='undocardreview',
            name='card_snapshot',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
