# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:40
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    # TODO: Port legacy_template to template before rerunning these, if ever. Otherwise suffer data loss (again).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0010_auto_20160823_0307'),
    ]

    operations = [
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='card',
            name='legacy_template',
        ),
    ]
