# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0012_remove_facttype_parent_fact_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fieldtype',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='fieldtype',
            name='fact_type',
        ),
    ]
