# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 03:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0014_delete_unused_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtype',
            name='transliteration_field_type',
        ),
        migrations.DeleteModel(
            name='FieldType',
        ),
    ]
