# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0015_auto_20160826_0302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='leech',
        ),
    ]
