# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 16:09
from __future__ import unicode_literals

from django.db import migrations, models


def copy_duration(apps, schema_editor):
    CardHistory = apps.get_model('flashcards', 'CardHistory')
    for card_history in CardHistory.objects.all():
        card_history.n_duration = card_history.duration
        card_history.save()


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0017_remove_deck_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardhistory',
            name='n_interval',
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(copy_duration),
    ]
