# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0021_auto_20160903_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='forked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fact',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='flashcards.Deck'),
        ),
    ]
