# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 17:12
from __future__ import unicode_literals

from django.db import migrations


def copy_contents_from_upstream(apps, schema_editor):
    Fact = apps.get_model('flashcards', 'Fact')
    for fact in Fact.objects.exclude(forked=True).iterator():
        if fact.synchronized_with is None:
            continue

        upstream = fact.synchronized_with
        if (
            fact.expression != upstream.expression or
            fact.reading != upstream.reading or
            fact.meaning != upstream.meaning
        ):
            if fact.expression or fact.reading or fact.meaning:
                self.forked = True
                fact.save(update_fields=['forked'])
            else:
                fact.expression = upstream.expression
                fact.reading = upstream.reading
                fact.meaning = upstream.meaning
                fact.forked = False
                fact.save(update_fields=['expression', 'reading', 'meaning', 'forked'])


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0022_add_forked_field'),
    ]

    operations = [
        migrations.RunPython(copy_contents_from_upstream),
    ]
