# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 23:34
from __future__ import unicode_literals

from django.db import migrations


def forwards(apps, schema_editor):
    Deck = apps.get_model('flashcards', 'Deck')

    for deck in Deck.objects.filter(active=False).order_by('id').iterator():
        print "Deactivating deck", deck.id
        for fact in deck.facts.iterator():
            fact.card_set.update(active=False)
        deck.facts.update(active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0023_copy_fact_contents_from_upstream'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
