# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-02 16:09
from __future__ import unicode_literals

import re

from django.db import migrations


def new_reading(reading):
    '''
    We were missing any readings after the first one.
    '''
    updated = re.sub(ur'[ 　,](\w+)\[([\w、／/ 　。－・,-]*)\]', ur'｜\1《\2》',
                     reading, flags=re.UNICODE)
    if reading != updated:
        print reading, "  ====>  ", updated
    return updated


def convert(apps, schema_editor):
    Fact = apps.get_model('flashcards', 'Fact')
    for fact in Fact.objects.all().iterator():
        reading = new_reading(fact.reading)
        Fact.objects.filter(id=fact.id).update(reading=reading)


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0024_deactivate_cards_in_inactive_decks'),
    ]

    operations = [
        migrations.RunPython(convert),
    ]
