# -*- coding: utf-8 -*-

NEXT_CARDS_TO_REVIEW_STUBS = [
    {
        "cards": [
            {
                "id": 15726,
                "deck": 370,
                "fact": 8112,
                "ease_factor": None,
                "interval": None,
                "due_at": None,
                "last_ease_factor": None,
                "last_interval": None,
                "last_due_at": None,
                "review_count": 0,
                "template": 0,
                "expression": u"[1] 汽車",
                "reading": u"｜汽車《きしゃ》",
                "meaning": "steam locomotive",
            },
            {
                "id": 15760,
                "deck": 370,
                "fact": 8146,
                "ease_factor": None,
                "interval": None,
                "due_at": None,
                "last_ease_factor": None,
                "last_interval": None,
                "last_due_at": None,
                "review_count": 0,
                "template": 0,
                "expression": u"[2] 左手",
                "reading": u"｜左手《ひだりて》",
                "meaning": "left hand",
            },
        ],
        "interstitial": None,
    },
    {
        "cards": [
            {
                "id": 15768,
                "deck": 370,
                "fact": 8154,
                "ease_factor": None,
                "interval": None,
                "due_at": None,
                "last_ease_factor": None,
                "last_interval": None,
                "last_due_at": None,
                "review_count": 0,
                "template": 0,
                "expression": u"[3] あせる",
                "reading": u"あせる",
                "meaning": "fret; be impatient",
            },
            {
                "id": 15819,
                "deck": 370,
                "fact": 8203,
                "ease_factor": None,
                "interval": None,
                "due_at": None,
                "last_ease_factor": None,
                "last_interval": None,
                "last_due_at": None,
                "review_count": 0,
                "template": 0,
                "expression": u"[4] おぼろな",
                "reading": u"おぼろな",
                "meaning": "hazy; indistinct",
            },
        ],
        "interstitial": {
            "more_cards_ready_for_review": True,
            "next_new_cards_count": 10,
        },
    },
]
